class ConstLists {
  List<String> stateList = [
    'Select option',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Iowa',
    'Kansas',
    'Louisiana',
    'Maine',
    'Massachusetts',
    'Michigina',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wiscnonsin',
    'Wyoming',
  ];
  List<String> genderEnglish = [
    'Select option',
    'Female',
    'Male',
    'Trans Female',
    'Trans Male',
    'Genderqueer / Gender Non-Binary',
    'Not Listed',
    'Prefer not to say',
  ];
  List<String> sexEnglish = [
    'Select option',
    'Male',
    'Female',
    'Other',
  ];
  List<String> raceEnglish = [
    'Select option',
    'American Indian or Alaska Native',
    'Asian',
    'Black or African American',
    'Native Hawaiian or Other Pacific Island',
    'White',
    'More than one race',
    'Unknown',
  ];
  List<String> ethnicityEnglish = [
    'Select option',
    'Hispanic or Latino',
    'Non Hispanic or Latino',
  ];
  //TODO Change it to spanish
  // List<String> genderEnglish = [
  //   'Female',
  //   'Male',
  //   'Trans Female',
  //   'Trans Male',
  //   'Genderqueer / Gender Non-Binary',
  //   'Not Listed',
  //   'Prefer not to say',
  //   'Select option',
  // ];
  // List<String> sexEnglish = [
  //   'Male',
  //   'Female',
  //   'Other',
  //   'Select option',
  // ];
  // List<String> raceEnglish = [
  //   'American Indian or Alaska Native',
  //   'Asian',
  //   'Black or African American',
  //   'Native Hawaiian or Other Pacific Island',
  //   'White',
  //   'More than one race',
  //   'Unknown',
  //   'Select option',
  // ];
  // List<String> ethnicityEnglish = [
  //   'Hispanic or latino',
  //   'Non Hispanic',
  //   'Select option',
  // ];
}
